### PR TITLE
Muthu/matcher lsh

### PR DESCRIPTION
**Pull request by cmkumar87**
- Locality Sensitive Hashing implements Cosine Similarity with Random Projection
- Adds dependency on library https://github.com/pixelogik/NearPy
- Branch doesn't track main.py; needs code in Master to run end-to-end

### CODE REVIEW

**Comment by wammar** [comment]
This PR seems to include many of the changes that Kyle merged, making it hard to review. Any idea why this is happening?

**Comment by cmkumar87** [comment]
I merged commits from Kyle's branch so I have the pipeline and main to run the matcher end-to-end. I can point to the files that need to be reviewed. Would that suffice?

**Comment by wammar** [comment]
Let's wait until Kyle merges his branch with `master` then rebase this branch so that it only has the new commits.

**Comment by wammar** [comment]
Looks like he already did. I'm updating this branch now so that it only contains the new commits.

**Pull request closed without merging**
